### ISSUE TITLE
Disabling headline highlight doesn't work

### ISSUE THREAD

**Issue by ourigen** [lukas-reineke/headlines.nvim#1]
First, thanks for this plugin! I was looking for a way to highlight SRC blocks in a different color just yesterday. However, I don't want headlines to be highlighted so I have in my config this

```
require("headlines").setup{
	org = {
		headline_signs = nil
	}
}
```

This doesn't seem to work since my headlines are still the color of ColorColumn. Am I misconfiguring the setup?

**Comment by lukas-reineke** [comment]
Sorry it should be `false` not `nil`
I'll update the documentation

**Comment by ourigen** [comment]
That worked, thanks!
