### ISSUE TITLE
Skip heading pattern in code blocks 

### ISSUE THREAD

**Issue by tami5** [lukas-reineke/headlines.nvim#14]
Hey @lukas-reineke, not sure if this is a bug I'm only experiencing because of my setup or it isn't indeed a known issue. 

Basically, whenever I have # in code block I endup with empty space under it.

![Screen Shot 2022-03-10 at 4 20 49 AM](https://user-images.githubusercontent.com/65782666/157568301-033c0802-895f-43a6-85ef-deeedbb84715.png)

is there away to disable this

Thanks

**Comment by lukas-reineke** [comment]
That was a bug, should be fixed now.
Thank you for reporting

**Comment by tami5** [comment]
❤️ Thanks so much @lukas-reineke
