### ISSUE TITLE
A popup covers editing line when there is no empty line underneath the header

### ISSUE THREAD

**Issue by ryuheechul** [lukas-reineke/headlines.nvim#17]
It's best illustrated with a screenshot I prepared them below

<img width="250" alt="Screen Shot 2022-04-07 at 5 27 03 PM" src="https://user-images.githubusercontent.com/2637709/162340099-85918f48-fe62-4d4a-9bb6-7fb9aed701bb.png">
<img width="254" alt="Screen Shot 2022-04-07 at 5 27 17 PM" src="https://user-images.githubusercontent.com/2637709/162340103-67ceb441-9f41-4db8-ba63-d98a8aab8e91.png">

_by space I mean empty line_

By the way I really like that `headlines.vim` puts the extra virtual line underneath which makes it look nicer when I'm editing without having to create an actual line. But unfortunately I discovered this bug with it and just wanted to share that here.

The popup is coming from [`hrsh7th/nvim-cmp` with `ghost_text = true`](https://github.com/hrsh7th/nvim-cmp/blob/27970d8a1c99cd6ddea2709beda52d8e9336228b/doc/cmp.txt#L682) (although I confirmed that it's the same result with `ghost_text = false` too)

**Comment by lukas-reineke** [comment]
I can confirm :+1: 
But this is not a bug here, it's a bug in cmp.

**Comment by ryuheechul** [comment]
> I can confirm 👍
> But this is not a bug here, it's a bug in cmp.

Hi @lukas-reineke, thanks for your comment and I will go ahead and open a issue there.
