### ISSUE TITLE
"Error running config with headlines.nvim, attempt to call a nil value" with neovim nightly build 0.8.0

### ISSUE THREAD

**Issue by aj3423** [lukas-reineke/headlines.nvim#20]
My config:
```lua
	-- syntax highlight for markdown
	use {
		'lukas-reineke/headlines.nvim',
		config = function()
		  require('headlines').setup()
		end,
	}
```
There is an error when it launches:
![image](https://user-images.githubusercontent.com/4710875/165581969-06f55a9d-82ef-4202-b2ae-46b194f38b3a.png)

**Comment by lukas-reineke** [comment]
Your config is fine. Are you sure it's installed correctly?

**Comment by aj3423** [comment]
After a reinstall and 'PackerSync' and a reboot, it works fine now, no error anymore. Sorry for bothering.
