### ISSUE TITLE
No parser for norg/org during setup

### ISSUE THREAD

**Issue by Gelio** [lukas-reineke/headlines.nvim#26]
Hey!

I'm afraid the latest changes from https://github.com/lukas-reineke/headlines.nvim/commit/64d4de9155e0b6cfec2b85ecf85d930fef8becff and https://github.com/lukas-reineke/headlines.nvim/commit/3ced1ced257f88b365e2f15bb4239739e4f6da52 expect users to have installed the treesitter parsers for filetypes that this plugin augments.

I don't use orgmode or neorg, so I didn't have treesitter parsers for `norg` and `org`. When starting nvim, I see the following error message:

```
packer.nvim: Error running config for headlines.nvim: ...local/share/nvim/runtime/lua/vim/treesitter/language.lua:25: no parser for 'org' language, see :help treesitter-parsers
```

I saw the same for `norg` earlier.

It would be more user-friendly to check that the parser exists before calling `vim.treesitter.parse_query` for that parser. This would not require users to install parsers for filetypes they don't use

**Comment by lukas-reineke** [comment]
I released a fix for this

**Comment by Gelio** [comment]
Thanks!
