### ISSUE TITLE
Custom query does not apply

### ISSUE THREAD

**Issue by gerritvreeman** [lukas-reineke/headlines.nvim#32]
Thanks for this wonderful plugin! I'm trying to set up a custom query to grab lower case "#+begin_src" blocks from orgmode, but I can't seem to apply any kind of custom query, even the defaults. The error given is:
```
attempt to call method 'iter_matches' (a nil value)
```
in the refresh function.

My setup function mirrors the defaults:
```lua
require("headlines").setup({
    org = {
        query = vim.treesitter.parse_query(
            "org",
            [[
        (headline (stars) @headline)

        (
        (expr) @dash
        (#match? @dash "^-----+$")
        )

        (block
        name: (expr) @_name
        (#eq? @_name "SRC")
        ) @codeblock
        ]]
        ),
        headline_highlights = { "Headline" },
        codeblock_highlight = "CodeBlock",
        dash_highlight = "Dash",
        dash_string = "-",
        fat_headlines = true,
    },
})
```
Without passing the config through the setup function, I don't get any errors.

I tried doing some diagnoses in the M.setup function, and it looks like when merging M.config[lang].query and config[lang].query a `<metatable>` is dropped that contains an `iter_matches` function. Perhaps this is unintended from `vim.tbl_deep_extend`?

**Comment by lukas-reineke** [comment]
Thanks,
I released a fix for this in https://github.com/lukas-reineke/headlines.nvim/releases/tag/v3.2.0
I also updated the query for org to include lowercase `src` by default.
