### ISSUE TITLE
Gaps within the fat headlines

### ISSUE THREAD

**Issue by pkazmier** [lukas-reineke/headlines.nvim#36]
Any idea why I'm getting these gaps within the bottom of the fat headlines?

<img width="773" alt="image" src="https://user-images.githubusercontent.com/747855/179324161-3612ec1b-ae4f-4432-88e7-57afc0f1cbec.png">

**Comment by lukas-reineke** [comment]
Your font/terminal renders the default character different to how it "should" look like.
I added an option for this in https://github.com/lukas-reineke/headlines.nvim/releases/tag/v3.3.0 now, so you can change it to something else.

**Comment by cultab** [comment]
Commenting to share the characters that worked for me when the default ones looked like in OP:

```lua
fat_headline_upper_string = "▄",
fat_headline_lower_string = "▀"
```

**Comment by GitMurf** [comment]
@cultab thank you for those characters you shared! works nicely for me on windows 11 in windows terminal!
