### ISSUE TITLE
Weird graphical problems

### ISSUE THREAD

**Issue by andreadev-it** [lukas-reineke/headlines.nvim#38]
Hello, I'm interested in using this plugin, but for some reason I cannot get it to work on my machine.
This is tested on Windows 10, with nvim 0.7.2

This is how an expanded org file looks like when I use the plugin:
![orgfile-problems](https://user-images.githubusercontent.com/68549121/179463180-25414c39-c457-41e4-a10f-eddcde7ba604.png)

This is how it should look (without colored headlines):
![orgfile-correct](https://user-images.githubusercontent.com/68549121/179463471-69c54c26-f1a7-47dd-a68f-5c8c3dd8b234.png)

I've also tried to copy the configuration including the treesitter query, but it didn't work. I then tried simplifying the query leaving only the headlines, but even that wouldn't fix the problem. At last, I tried removing the org-bullets plugin, but it didn't change anything either.

How can I fix this problem?

**Comment by lukas-reineke** [comment]
Your font/terminal renders the default character different to how it "should" look like.
I added an option for this in https://github.com/lukas-reineke/headlines.nvim/releases/tag/v3.3.0 now, so you can change it to something else.

**Comment by andreadev-it** [comment]
I changed the characters used and indeed it's better. It only still has problems when the org document is folded (some lines and headings disappear), but only if fat headlines are used. I've just disabled those and it's fine for me.

**Comment by lukas-reineke** [comment]
Can you open a new issue for the folding bug?

**Comment by kavinvalli** [comment]
@lukas-reineke Can you tell which font will this character work with?

**Comment by GitMurf** [comment]
> ...It only still has problems when the org document is folded (some lines and headings disappear), but only if fat headlines are used. I've just disabled those and it's fine for me.

@andreadev-it did you ever get to the bottom of this? I seem to be having the same problems with stuff disappearing when folding and it appears turning off fat headlines also solves it for me.

@lukas-reineke I know this thread was from a year ago and you had asked for another gh issue to be opened. Did that ever happen? is this something that has been reported or addressed anywhere else before I bring this back to the surface as an issue? Thanks!

**Comment by GitMurf** [comment]
@lukas-reineke fyi here is a reproduction of what I am talking about and I think what @andreadev-it was talking about last year. Let me know if you have any questions and/or if you need anything else from me and/or if you think this should be opened as a new gh issue?

I have the exact same org file opened on left and right. The first one on left is with the fat headlines turned off. You see when I fold the second headline and navigate up and down everything looks fine and as expected.

But then when I move to the example on the right, where fat headlines is turned on, you see when I fold and then move up and down I get a bunch of weird disappearing text at different times as I move up and down with my cursor.

https://github.com/lukas-reineke/headlines.nvim/assets/64155612/8aadef2f-ccc3-49db-a088-a3dcf79f9bcc

**Comment by andreadev-it** [comment]
Hi, sorry for not giving any updates about this. In the end, I just decided to not use that plugin and keep the default headlines. This means that I didn't actually understood what caused the error in the first place

**Comment by GitMurf** [comment]
> Hi, sorry for not giving any updates about this. In the end, I just decided to not use that plugin and keep the default headlines. This means that I didn't actually understood what caused the error in the first place

@andreadev-it no worries! Thanks for the quick response. Do you recall if the issues you were seeing were similar to what my video shows above? Thanks!!

**Comment by andreadev-it** [comment]
I've seen the video, but I'm not sure it was the same effect I was experiencing... If I recall correctly, some headings disappeared incorrectly when folding too
