### ISSUE TITLE
indentation guides and showbreak chars don't have the right background in codeblocks

### ISSUE THREAD

**Issue by chrisgrieser** [lukas-reineke/headlines.nvim#44]
Thanks for the nice plugin, makes navigating big markdown files a bit easier.

indention guides (from [indent-blankline](https://github.com/lukas-reineke/indent-blankline.nvim)) and fillchars/showbreak characters do not get the proper background, resulting in weird "holes" when in codeblocks

![image](https://user-images.githubusercontent.com/73286100/210184145-1c66aeab-798a-47ab-a12b-2c568411c0a0.png)

**Comment by lukas-reineke** [comment]
Those highlight groups probably have an explicit background color set.

The linebreak should be `NonText`, so you can check with `:highlight NonText`.
If it has a background color, remove it with `:highlight NonText guibg=None`

**Comment by chrisgrieser** [comment]
Hmm, does not look like it
<img width="993" alt="image" src="https://user-images.githubusercontent.com/73286100/210732008-b38d783d-9c9a-4248-941f-77466b0bbdc4.png">
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/73286100/210732327-7fb2d208-63c5-45d1-a385-e808b29ba40c.png">

**Comment by illumiko** [comment]
> Hmm, does not look like it <img alt="image" width="993" src="https://user-images.githubusercontent.com/73286100/210732008-b38d783d-9c9a-4248-941f-77466b0bbdc4.png"> <img alt="image" width="1357" src="https://user-images.githubusercontent.com/73286100/210732327-7fb2d208-63c5-45d1-a385-e808b29ba40c.png">

 It seems to me that the linebreaks's highlight isnt following the guibg of the codeblock

**Comment by adrian5** [comment]
> <details><summary>Screenshots</summary>
> <img alt="image" width="993" src="https://user-images.githubusercontent.com/73286100/210732008-b38d783d-9c9a-4248-941f-77466b0bbdc4.png"> <img alt="image" width="1357" src="https://user-images.githubusercontent.com/73286100/210732327-7fb2d208-63c5-45d1-a385-e808b29ba40c.png">
</details>

@chrisgrieser Sorry for being offtopic, but which theme is this? I looked at your dotfiles, but it doesn't quite match Nightfox, nor Tokyo Night. Thanks!

**Comment by chrisgrieser** [comment]
Hmm, the issue does not occur for me anymore with the new version of indent-blank lines. So if no one else has it, I guess this can be closed.
