### ISSUE TITLE
Bug: Example org setup in README is missing comma

### ISSUE THREAD

**Issue by grantwinship-consulting** [lukas-reineke/headlines.nvim#5]
I believe you're missing a comma here:
`vim.fn.sign_define("Headline2"  { linehl = "Headline2" })`
`vim.fn.sign_define("Headline2", { linehl = "Headline2" })`

**Comment by lukas-reineke** [comment]
Your right, do you want to make a PR?

**Comment by grantwinship-consulting** [comment]
Thanks @francium for grabbing that sorry i've been on the road
