### ISSUE TITLE
markdown: bullet lists don't play nice with block quotes and code blocks

### ISSUE THREAD

**Issue by tomtomjhj** [lukas-reineke/headlines.nvim#52]
With the default config `require("headlines").setup()` and everything (nvim, nvim-treesitter, markdown parser, markdown_inline parser, ..) up-to-date, I get the following behaviors from markdown.

## block quote + list
code
<pre>
* list item
  > quote line 1
  > quote line 2. The bar is misplaced and ">" is not hidden.
</pre>
Result
![image](https://user-images.githubusercontent.com/19489738/229337990-66bfc1f5-3236-4ea5-bbb7-61a0e65f41d4.png)

## code block + list
code
<pre>
* item 1
  ```
  code block
  ```
* this item's bullet is hidden
</pre>
Result
![image](https://user-images.githubusercontent.com/19489738/229338082-0234632a-7a21-408c-ac15-d099e39cea1a.png)

**Comment by francium** [comment]
#48 and this (#52) also affect me.

@lukas-reineke I'm happy to sponsor you if it will help you allocate time or motivation to work on these two issues

**Comment by tomtomjhj** [comment]
@francium try #54

**Comment by francium** [comment]
@tomtomjhj Thanks, it's working really well as far as I cant tell

**Comment by ronisbr** [comment]
Hi!

I am also having this issue. Is there any work around at the moment?

**Comment by lukas-reineke** [comment]
Forgot to merge the PR :facepalm: 
should be fixed now, thanks for the reminder
