### ISSUE TITLE
Weird color behavior on light theme

### ISSUE THREAD

**Issue by niceiq** [lukas-reineke/headlines.nvim#60]
When I first launch Neovim on a markdown file, the color kind of glitches: 
![image](https://github.com/lukas-reineke/headlines.nvim/assets/98485752/3a1714a6-97e9-4614-ba18-b46ffcad0046)

I can fix it by opening Left Explorer and closing it, but as you can imagine, this is pretty annoying.

This is the expected result: 
![image](https://github.com/lukas-reineke/headlines.nvim/assets/98485752/061e7a77-447b-4c2a-9363-80e547a2d161)

This issue started to occur when I switched to a light theme terminal. I use Alacritty.

**Comment by lukas-reineke** [comment]
please provide steps to reproduce the issue

**Comment by niceiq** [comment]
I have fixed my issue, I forget to set the Neovim theme to light, I only had the terminal theme that was light.

I will close the issue.
