### ISSUE TITLE
fat_headline_lower_string not working

### ISSUE THREAD

**Issue by ssossah** [lukas-reineke/headlines.nvim#61]
Hello, fat_headline_lower_string isn't rendering as expected (I am trying to get this to work for neorg specifically). The current implementation just renders it as a box with a question mark inside:
<img width="288" alt="image" src="https://github.com/lukas-reineke/headlines.nvim/assets/132931639/3572634b-4e0a-41b2-85c5-519d0993d6da">
What can I do to get it to render as expected?

Also, is there a way to only highlight "Headline1" and "Headline2" rather then highlighting subsequent headlines?

Any help would be greatly appreciated!

**Comment by lukas-reineke** [comment]
> box with a question mark inside

This means the font you are using doesn't support this character. Either use a different font, or use a different character.

> Also, is there a way to only highlight "Headline1" and "Headline2" rather then highlighting subsequent headlines?

You can overwrite the query to only include the first 2 headlines.

**Comment by reegnz** [comment]
@lukas-reineke could you please mention a font name that the default config displays properly with?

**Comment by rscircus** [comment]
Same here. Patched my font with nerd-font patcher and it is missing.

**Comment by JoseIgnacioGC** [comment]
I recommend using the `▀` character.

``` lua
-- example config
markdown = {
    fat_headline_lower_string = "▀",
}
```
