### ISSUE TITLE
not "remove" inline style chars

### ISSUE THREAD

**Issue by JonatasAmaral** [lukas-reineke/headlines.nvim#67]
I got the point of hiding some stylizing chars on preview, so \`code\` -> `code` when not editing that line.

![image](https://github.com/lukas-reineke/headlines.nvim/assets/8677724/a4cad47b-37f9-4d49-853b-fbad87b3571a)
![image](https://github.com/lukas-reineke/headlines.nvim/assets/8677724/5abebd7c-aae7-4f48-a4cd-7694358e81c5)

It's real nice.

But this also make some work with thing a bit wonky, specially in tables
Where **some** text changes size, and get misaligned.

![image](https://github.com/lukas-reineke/headlines.nvim/assets/8677724/dcb40bb9-30a6-4c45-931e-1a9c32b07256)

![image](https://github.com/lukas-reineke/headlines.nvim/assets/8677724/6cf2cbdc-d42d-42c3-b854-dee334de7751)

I aware of the potential awkward extra spacing, but maybe could it be that those char could only be replaced by blank ones, so spacing remains?
Or any otter ideas here.
Maybe prevent that only inside tables?!

Some example of what i'm talking:

* Code block hide the ticks, but dont collapse de line, giving it an extra "border" on top and bottom.
  ![image](https://github.com/lukas-reineke/headlines.nvim/assets/8677724/83675659-2247-4a21-b1f9-ab9e3fecaf9d)

* Quotes change the char/symbol, but spacing remains the same.
  ![image](https://github.com/lukas-reineke/headlines.nvim/assets/8677724/33616662-7bd5-400f-bf99-b32092848f50)

**Comment by lukas-reineke** [comment]
That hiding of characters is not from headlines.nvim. That is Neovims build in `:help conceal` and treesitter.
