### ISSUE TITLE
A problem with headers

### ISSUE THREAD

**Issue by foozzi** [lukas-reineke/headlines.nvim#74]
![image](https://github.com/lukas-reineke/headlines.nvim/assets/1178208/54e449be-9861-4e71-bd3a-4d79eb9ece48)

How can I fix it?

`NVIM v0.9.5`
`alacritty 0.13.1`

**Comment by matthewcarbone** [comment]
@foozzi I'm having this same issue. Mind sharing how you fixed it?

**Comment by foozzi** [comment]
> @foozzi I'm having this same issue. Mind sharing how you fixed it?

```lua
return {
	"lukas-reineke/headlines.nvim",
	dependencies = "nvim-treesitter/nvim-treesitter",
	opts = {
		markdown = {
			fat_headline_lower_string = "▔",
		},
	},
}
```
just change the symbol
