### ISSUE TITLE
Scrolling in markdown file leads to neovim exit with error code -134

### ISSUE THREAD

**Issue by LinoWhy** [lukas-reineke/headlines.nvim#78]
First of all, thanks for developing headlines (and also indent-blankline)! These two are the must-have plugins in my neovim configuration.

Occasionally I find a bug with headline related. Trigger buffer scolling with control-f, makes neovim exit with error code -134.
![image](https://github.com/lukas-reineke/headlines.nvim/assets/43626684/c5231778-ae51-4772-9c22-e2244dabf568)

The problem only occurs if I running neovim nightly pre-release, with headline.nvim enabled. Works without error for:
- neovim 0.9.0+ and headline.nvim enabled
- neovim nightly and headline.nvim disabled

**Comment by lukas-reineke** [comment]
Can reproduce, it's a bug in Neovim
I opened a ticket https://github.com/neovim/neovim/issues/28290

**Comment by lukas-reineke** [comment]
Fixed in core, closing
