### ISSUE TITLE
Bug in init.lua

### ISSUE THREAD

**Issue by xorander00** [lukas-reineke/headlines.nvim#8]
lua/headlines/init.lua:121  
M.dash_namespace should be M.namespace.  
I just patched it locally after figuring out why it was bombing. If you want me to send a PR, I can do that a bit later. It's small enough though to make the change super quick.  
  
Thanks for the plugin, I like it!

**Comment by lukas-reineke** [comment]
Thank you!
I quickly fixed it myself now, I don't want to leave it broken.

Next time, just open a PR directly :rocket:
