### ISSUE TITLE
Bug: README uses the non-existent function vim.treesitter.parse_query

### ISSUE THREAD

**Issue by Terseus** [lukas-reineke/headlines.nvim#86]
The README examples are using the non-existent function `vim.treesitter.parse_query`.

It should be changed to [vim.treesitter.query.parse](https://neovim.io/doc/user/treesitter.html#vim.treesitter.query.parse()).

**Comment by Aman9das** [comment]
https://github.com/lukas-reineke/headlines.nvim/pull/76 fixes it.

**Comment by Terseus** [comment]
Indeed, thanks for the work @GaetanLepage, and thanks @Aman9das for pointing it out.
