### ISSUE TITLE
Fat Headline not visible when Headlines are touching in org mode.

### ISSUE THREAD

**Issue by theshatterstone** [lukas-reineke/headlines.nvim#91]
I'm not sure if this is intentional or not, but when multiple Headlines are touching because they are collapsed or because they are simply written next to each other, the fat headline disappears at the point of contact. Is there a way to stop this from happening? Thanks

Screenshots below: 
![2024-08-15T15:52:33,694838644+01:00](https://github.com/user-attachments/assets/56fdc943-ca8c-48c0-9556-ce05509118a8)
![2024-08-15T15:52:47,603969259+01:00](https://github.com/user-attachments/assets/7f6c64b8-7636-45b3-8940-69e5fee2ee35)

**Comment by lukas-reineke** [comment]
That is because what you see are not the actual headlines anymore. That's just `:help 'foldtext'`

Foldtext is not really in the buffer, so there is also no way to target it with treesitter. This won't be supported.
